apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketapp-421100
  artifacts:
    - image: josephlee01/auth
      # - image: us.gcr.io/ticketapp-421100/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: josephlee01/client
      # - image: us.gcr.io/ticketapp-421100/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: josephlee01/tickets
      # - image: us.gcr.io/ticketapp-421100/auth
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: josephlee01/orders
      # - image: us.gcr.io/ticketapp-421100/auth
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: josephlee01/expiration
      # - image: us.gcr.io/ticketapp-421100/auth
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: josephlee01/payments
      # - image: us.gcr.io/ticketapp-421100/auth
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
